-- Structure du Vide : penchée de 6° sur sa droite et de 5° vers l'avant.
-- Kiosque du Vide : réduit à 0,8, penché de 5° vers l'avant et de 6° sur sa gauche.
--
-- Ni l'échelle ni l'assiette d'un gameobject n'atteignent un objet de carte : le client n'en garde
-- que le lacet. Tout est donc dans le fichier, par redimensionner_wmo.py et tourner_wmo.py — roulis
-- autour de +X, qui amène le haut vers -Y, la droite du modèle, donc un angle négatif pour la
-- gauche ; tangage autour de +Y, qui l'amène vers +X, son avant.
--
-- Chaque réglage repart de la copie d'origine, jamais de la version déjà transformée : sinon les
-- angles et les facteurs se cumulent.
--
-- L'arbre de collision est reconstruit après chaque rotation, ses plans étant alignés sur les axes.
-- Chaque face y est référencée une fois et une seule.
--
-- Boîtes d'affichage : 47607 -26.66, -35.78, -6.36, 27.16, 36.04, 73.37 ; 47622 -29.07, -29.04, -5.19, 28.77, 28.70, 40.60.
UPDATE `gameobject_template` SET `size` = 1 WHERE `entry` IN (2600011, 2600028);
