-- Le pavillon posé à Dalaran disparaissait dès qu'on s'éloignait au-dessus de la Grande Mer.
--
-- Ce n'est pas le client : c'est la portée serveur. `GameObject::Create` recopie
-- `VisibilityDistance` dans `m_visibilityDistanceOverride`, et `WorldObject::GetSightRange` la rend
-- telle quelle — elle passe même avant `MaxVisible`, qui plafonnerait à GLOBAL_VISIBILITY_DISTANCE,
-- soit 1 000 yards. À 1 200 l'objet sortait de portée dès qu'on quittait la cité, qui flotte à plus
-- de 600 yards au-dessus de l'eau.
--
-- 5 000 couvre largement Dalaran et ses abords. `MaxVisible` reste indispensable : c'est lui qui
-- sort l'objet du parcours des grilles, sans quoi la portée serait rabotée à la taille d'une grille.
UPDATE `gameobject_template` SET `VisibilityDistance` = 5000 WHERE `entry` IN (2600051, 2600052);
