-- ==========================================================================================
-- Azerite Rush - let the airships actually be started again
--
-- MapInstanced::CreateBattleground force stops every instance transport it spawns. The mode
-- calls Transport::EnableMovement(true) to undo that, but:
--
--   void Transport::EnableMovement(bool enabled)
--   {
--       if (!GetGOInfo()->moTransport.allowstopping)
--           return;
--       _pendingStop = !enabled;
--   }
--
-- With Data8 (allowstopping) at 0 the call returned immediately, _pendingStop stayed true and
-- Transport::Update never advanced PathProgress. The ships were frozen at their first keyframe
-- server side, while the client - which owns a copy of the path - animated them anyway and got
-- snapped back on every position update. That is the "reset" that never completed a lap.
--
-- Data8 = 1 makes the flag meaningful and EnableMovement effective. Data9 (InitStopped) stays 0.
-- ==========================================================================================

UPDATE `gameobject_template` SET `Data8` = 1 WHERE `entry` IN (900001, 900002);
