-- The world map id is withdrawn: it crashes the client.
--
-- Update 2026_09_08_15 set UiWorldMapAreaID to 1206 on the Wound's phase definitions. It was
-- applied at 00:51:03 and the client crashed at 00:51:40, then again at 00:52:01 and 01:00:11 -
-- three times, same instruction, same faulting address 0x36, always on map 1. Nothing else had
-- changed; the light substitution it shared the session with had been running since 21:49 without
-- a single crash, so the timing rules it out and names this one.
--
-- Reading a field off address 0x36 is a null dereference: the client resolves the id, gets nothing
-- back, and reads into it anyway. The likely reason is that the last vector of SMSG_SET_PHASE_SHIFT
-- is not a WorldMapArea list at all - 7.3.5 has no UiMapPhase.db2 for it to resolve against, so
-- feeding it a WorldMapArea id sends it looking somewhere that has no such row.
--
-- The map art exists and is worth another attempt, but not through this field and not blind.
UPDATE `phase_definitions` SET `UiWorldMapAreaID` = 0 WHERE `entry` IN (10, 4600) AND `UiWorldMapAreaID` = 1206;
