-- La Structure du Vide écrase la plateforme : réduite de moitié.
--
-- Pas par `size` : l'échelle d'un gameobject ne touche pas un WMO, le client dessine un objet de
-- carte à sa taille propre. Sur les gameobjects natifs, 18 seulement portent une échelle avec un
-- affichage WMO contre 19 313 avec un affichage M2, et plusieurs de ces 18 valent 0,0000000000000098
-- — le tour de passe-passe pour masquer un objet, pas une vraie échelle.
--
-- La géométrie est donc réduite dans le fichier même, par redimensionner_wmo.py : sommets, boîtes
-- englobantes, arbre de collision, placements et échelle propre des 573 accessoires. `size` revient
-- à 1 pour ne pas réduire deux fois si une version du client venait à l'honorer.
UPDATE `gameobject_template` SET `size` = 1 WHERE `entry` = 2600011;
